# Generated by Django 2.2 on 2020-10-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors_app', '0002_auto_20201010_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='phone_number',
            field=models.CharField(max_length=264),
        ),
    ]
