# Generated by Django 2.2 on 2020-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=264, unique=True)),
                ('case_type', models.CharField(max_length=264)),
                ('amount_needed', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
