# Generated by Django 2.2 on 2020-10-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='amount_needed',
            field=models.PositiveIntegerField(),
        ),
    ]
