# Generated by Django 2.2 on 2020-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_app', '0002_auto_20201009_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
