# Generated by Django 2.2 on 2020-10-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases_app', '0003_auto_20201010_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
