# Generated by Django 2.2 on 2020-11-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases_app', '0001_initial'),
        ('donors_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.PositiveIntegerField()),
                ('paid_flag', models.BooleanField()),
                ('case_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases_app.Cases')),
                ('donor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donors_app.Donors')),
            ],
        ),
    ]
